# Generated by Django 5.2.6 on 2025-09-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="updatedat",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("slug", models.SlugField(max_length=1000)),
                ("image", models.ImageField(upload_to="media")),
                ("short_description", models.CharField(max_length=10000)),
                ("detail_description", models.CharField(max_length=1000000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Publshed", "Published"), ("Drafted", "Drafted")]
                    ),
                ),
                ("is_trending", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.categories",
                    ),
                ),
            ],
        ),
    ]
